config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'} , :controllers => { :registrations => "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  

  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   user ||= User.new #guest user (not logged in)
   can :manage, User, id: user.id 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
  belongs_to :product
  
	validates :body, presence: true
	validates :user, presence: true
	validates :product, presence: true
	validates :rating, numericality: { only_integer: true }
  
  scope :rating_desc, -> { order(rating: :desc) }

  self.per_page = 5
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	has_many :orders
	has_many :comments

	def highest_rating_comment
		comments.rating_desc.first
	end
	
	def average_rating
  comments.average(:rating).to_f
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, :alert => exception.message
end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
  	@comment = @product.comments.new(comment_params)
  	@comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @product, notice: 'Review was created successfully'}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully'}
        format.json { render json: @comment.errors, status: :unprocessable_entity}
      end
    end
	end

	def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
	end

	private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter :authenticate_user!
	
	def index
	end

	def show
	end

	def new
	end

	def create
	end

	def destroy
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q] #return our filtered list here
      @products = Product.where("name ilike ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate( :page => params[:page])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  # def landing_page
  # 	@featured_product = Product.first
  # end

  def landing_page
  	@products = Product.limit(3)
	end

	# def thank_you
	#   @name = params[:name]
	#   @email = params[:email]
	#   @message = params[:message]
	#   ActionMailer::Base.mail(:from => @email,
	#       :to => 'miramaxeast@yahoo.com',
	#       :subject => "A new contact form message from #{@name}",
	#       :body => @message).deliver_now
	# end
	def thank_you
	  @name = params[:name]
	  @email = params[:email]
	  @message = params[:message]
	  UserMailer.contact_form(@email, @name, @message).deliver_now
	end

end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
  def create
    super
    if @user.persisted?
      UserMailer.welcome(@user).deliver_now
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

  </head>

  <body>
  	<nav class="navbar-collapse collapse">
  		<ul class="nav navbar-nav navbar-right">
  			<li><%= link_to "Home", static_pages_landing_page_path %></li>
  			<li><%= link_to "About", static_pages_about_path %></li>
  			<li><%= link_to "Contact", static_pages_contact_path %></li>
        <li class="nav-search">
          <%= form_tag("/products", method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
          <% end %>
        </li>  
      </ul>
      <ul class="nav pull-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
        </li>
      </ul>
  	</nav>

    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert" role="alert"><%= alert %></p>
    <% end %>
    

    <%= yield %>
    


    <footer>
    	&copy; 2016 Ayana Jewelry

      <div class="twitter"> <a href="https://twitter.com/Twitter" class="twitter-follow-button" data-lang="en" data-show-count="false">Follow @Twitter</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>

    
      <div class="fb-like" data-href="https://www.facebook.com/mira.max.184" data-layout="standard" data-action="like" data-size="small" data-show-faces="false" data-share="false"></div>


      <div class="fb-share-button" data-href="https://www.facebook.com/mira.max.184" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Fmira.max.184&amp;src=sdkpreparse">Share</a></div>

    </footer>
  </body>
</html>

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p>

            	<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>

            	<% if signed_in? && current_user.admin? %>
                    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                

                <% end %>

						</p>

						<div class="rated" data-score="<%= comment.rating %>"></div>
            	<p><%= "Rating: #{comment.rating}/5" %></p>
            	<p><%= comment.body %></p>
        		</div>
    <% end %>
</div>

<%= will_paginate @comments %>



    

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="product_name">Name</label><br>
    <input id="product_name" name="product[name]" type="text" />
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>

	<h4>Add a review:</h4>
	<%= form_for([@product, @product.comments.build], remote: true) do |f| %>

	  <p>
	    <%= f.label :body, "Comments" %><br>
	    <%= f.text_area :body %>
	  </p>

	  <p>
	  	<div class="rating"></div>
	  </p>

	  <p>
	    <%= f.submit "Submit" %>
	  </p>
	<% end %>

<% end %>

app/views/products/_product.html.erb
<div class="row">
    <div class="col-sm-2 col-md-4">
      <%= image_tag(product.image_url, size: "100x100", class: "img-responsive") %>
    </div>
    <div class="col-xs-12 col-md-6 text-center">
      <h2><%= product.name %></h2>
      <hr>
      <p><%= product.description %></p><br>
      <p><%= product.colour %></p>
      <p>$<%= product.price %></p>
      <%= link_to 'Show', product %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <hr>
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing products</h1>
<%= render @products %>

<%= link_to "New Product", new_product_path %>
<%= link_to "Product details", @product %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>  
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= @product.highest_rating_comment %>

<%= render 'comments' %>
<%= render 'new_comment' %>

app/views/static_pages/about.html.erb
<h1>Ayana Jewelry</h1>
<p>Ayana Jewelry is studio-boutique of fine contemporary jewelry</p>

app/views/static_pages/contact.html.erb
<h1>Ayana Jewelry</h1>
<p>Contact Us</p>

<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do %>
<div class="row">
  <div class="col-md-4">
    <div class="form-group">
      <%= label_tag :name %>
      <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
    </div>      
    <div class="form-group">
      <%= label_tag :email, "Email Address" %>
      <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
    </div>
    <div class="form-group">
      <%= label_tag :message %>
      <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
    </div>      
  </div>
</div>
<%= submit_tag "Send" %>   
<% end %>

app/views/static_pages/index.html.erb
<h1>Ayana Jewelry</h1>
<p>Welcome! The date and time is <%= Time.now %></p>
<%= image_tag("bride.jpg", class: "img-responsice my-image") %>
<%#= image_tag(product.image_url, class: "img-responsive") %>

<%# text_variable %>
<%#= text_variable %>

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<%#= @featured_product.name %>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <div class="carousel-caption">
        <%= product.name %>
      </div>
    </div>
    <% end %>

   <ol class="carousel-indicators">  
    <% @products.each do |product, i| %>  
    <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= "active" if product == @products.first %>"></li>  
    <% end %>  
  </ol>  

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>